
import "./globals.css";
import Header from "../components/Header";
import Home from "./page";


export const metadata = {
  title: "Soccer App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Header />
        
        {children}
      </body>
    </html>
  );
}
